version: '2.1'
networks: {}
volumes:
  muco-data: {}
services:
  radio_house:
    build:
      context: ./mopidy
    privileged: true
    tty: true
    restart: always
    ports:
      - '6691:6680'
      - '6611:6600'
    volumes:
      - 'muco-data:/data'
    depends_on:
      - 'snapserver'
    environment:
      - SNAPSERVER_PORT=6633
  radio_garden:
    build:
      context: ./mopidy
    privileged: true
    tty: true
    restart: always
    ports:
      - '6692:6680'
      - '6612:6600'
    volumes:
      - 'muco-data:/data'
    depends_on:
      - 'snapserver'
    environment:
      - SNAPSERVER_PORT=6634
  snapserver:
    build:
      context: ./snapserver
    privileged: true
    tty: true
    restart: always
    ports:
      - '1714:1704'
      - '1715:1705'
      - '1716:1706'
      - '1790:1780'
    volumes:
      - './muco-data/config:/etc/snapserver'
      - './muco-data/transfer:/tmp'  
  spocon:
    build:
      context: ./spocon
    restart: always
    privileged: true
    volumes:
      - './muco-data/config:/opt/librespot/config'
      - './muco-data/transfer:/tmp'
    ports:
      - '9993:9993'
      - '24879:24879'
