version: '2.4'
networks: {}
volumes:
  muco-data: {}
services:
  radio_house:
    build:
      context: ../src/mopidy
    restart: always
    ports:
      - '6691:6680'
      - '6611:6600'
    volumes:
      - 'muco-data:/data'
    depends_on:
      - 'snapserver'
    environment:
      - SNAPSERVER_PORT=6633
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
  radio_garden:
    build:
      context: ../src/mopidy
    restart: always
    ports:
      - '6692:6680'
      - '6612:6600'
    volumes:
      - 'muco-data:/data'
    depends_on:
      - 'snapserver'
    environment:
      - SNAPSERVER_PORT=6634
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
  snapserver:
    build:
      context: ../src/snapandlibre
    restart: always
    privileged: true
    ports:
      - '1714:1704'
      - '1715:1705'
      - '1716:1706'
      - '1790:1780'
      - '9993:9993'
      - '24879:24879'
    logging:
      driver: "json-file"
      options:
        max-size: "50m"   
    volumes:
      - './muco-data/snapserver/config:/opt/snapserver/config'
      - './muco-data/librespot/config:/opt/librespot/config'
