version: '2.1'
networks: {}
name: muco_server
volumes:
  muco-data: {}
services:
  radio_house:
    build:
      context: ../src/mopidy
    restart: always
    ports:
      - '6691:6680'
      - '6611:6600'
    volumes:
      - 'muco-data:/data'
    depends_on:
      - 'snapserver'
    environment:
      - SNAPSERVER_PORT=6633
  radio_garden:
    build:
      context: ../src/mopidy
    restart: always
    ports:
      - '6692:6680'
      - '6612:6600'
    volumes:
      - 'muco-data:/data'
    depends_on:
      - 'snapserver'
    environment:
      - SNAPSERVER_PORT=6634
  snapserver:
    build:
      context: ../src/snapandlibre
    restart: always
    ports:
      - '1714:1704'
      - '1715:1705'
      - '1716:1706'
      - '1790:1780'
      - '9993:9993'
      - '24879:24879'
    volumes:
      - './muco-data/snapserver/config:/opt/snapserver/config'
      - './muco-data/librespot/config:/opt/librespot/config'
  kitchen_client:
    build:
      context: ../src/snapclient
    privileged: true
    restart: always
    environment:
      - HOST=192.168.0.97
      - PORT=1714
      - HOST_ID=snapclient_kitchen
      - LATENCY=0
      - SOUNDCARD=default
  terrace_client:
    build:
      context: ../src/snapclient
    privileged: true
    restart: always
    environment:
      - HOST=192.168.0.97
      - PORT=1714
      - HOST_ID=snapclient_terrace
      - LATENCY=0
      - SOUNDCARD=18